[package]
name = "exercise-2"
version = "0.1.0"
authors = ["Selwyn <talk@selwyn.cc>"]
repository = "https://github.com/Siilwyn/code-class-js-rust"
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde = { version = "1.0", features = ["derive"] }
